server:
  port: 8080

spring:
  application:
    name: yx-lab-backend
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.7.17:3306/yx_lab?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: GlcLMg3SNPrTczvoRN
  redis:
    host: 192.168.7.108
    port: 6379
    database: 15
    password: CoOHvRWRlaBgb%Jf)R
    timeout: 5000ms
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

springdoc:
  swagger-ui:
    path: /swagger-ui.html

lab:
  security:
    token-header: Authorization
    token-prefix: Bearer
    token-expire-hours: 12
  storage:
    upload-dir: ./uploads
