-- 结构审计结论：
-- 1. 按仓库内当前建表脚本与实体映射核对，现有业务表均已存在主键字段 id，无需新增主键列。
-- 2. 本脚本用于统一补齐数据库表注释、字段注释，便于后续维护、导出与数据库可视化查看。
-- 3. 执行前请先确保已完成当前版本的基础建表与增量升级脚本。

ALTER TABLE lab_role COMMENT = '系统角色表';
ALTER TABLE lab_role
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID',
    MODIFY COLUMN role_code VARCHAR(32) NOT NULL COMMENT '角色编码',
    MODIFY COLUMN role_name VARCHAR(64) NOT NULL COMMENT '角色名称',
    MODIFY COLUMN role_scope VARCHAR(64) NULL COMMENT '角色适用范围',
    MODIFY COLUMN status TINYINT DEFAULT 1 COMMENT '状态，1启用，0停用',
    MODIFY COLUMN remark VARCHAR(500) NULL COMMENT '备注',
    MODIFY COLUMN deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记，0未删除，1已删除',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_name VARCHAR(64) NULL COMMENT '创建人名称',
    MODIFY COLUMN created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_name VARCHAR(64) NULL COMMENT '更新人名称',
    MODIFY COLUMN updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE lab_org COMMENT = '系统机构表';
ALTER TABLE lab_org
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID',
    MODIFY COLUMN org_code VARCHAR(32) NOT NULL COMMENT '机构编码',
    MODIFY COLUMN org_name VARCHAR(64) NOT NULL COMMENT '机构名称',
    MODIFY COLUMN parent_id BIGINT NULL COMMENT '上级机构ID',
    MODIFY COLUMN parent_name VARCHAR(64) NULL COMMENT '上级机构名称',
    MODIFY COLUMN org_type VARCHAR(64) NULL COMMENT '机构类型',
    MODIFY COLUMN status TINYINT DEFAULT 1 COMMENT '状态，1启用，0停用',
    MODIFY COLUMN remark VARCHAR(500) NULL COMMENT '备注',
    MODIFY COLUMN deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记，0未删除，1已删除',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_name VARCHAR(64) NULL COMMENT '创建人名称',
    MODIFY COLUMN created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_name VARCHAR(64) NULL COMMENT '更新人名称',
    MODIFY COLUMN updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE lab_dict COMMENT = '系统数据字典表';
ALTER TABLE lab_dict
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID',
    MODIFY COLUMN dict_code VARCHAR(64) NOT NULL COMMENT '字典编码',
    MODIFY COLUMN dict_name VARCHAR(64) NOT NULL COMMENT '字典名称',
    MODIFY COLUMN module_name VARCHAR(64) NOT NULL COMMENT '所属模块',
    MODIFY COLUMN item_text TEXT NULL COMMENT '字典项文本',
    MODIFY COLUMN status TINYINT DEFAULT 1 COMMENT '状态，1启用，0停用',
    MODIFY COLUMN remark VARCHAR(500) NULL COMMENT '备注',
    MODIFY COLUMN deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记，0未删除，1已删除',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_name VARCHAR(64) NULL COMMENT '创建人名称',
    MODIFY COLUMN created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_name VARCHAR(64) NULL COMMENT '更新人名称',
    MODIFY COLUMN updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE lab_user COMMENT = '系统用户表';
ALTER TABLE lab_user
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID',
    MODIFY COLUMN username VARCHAR(64) NOT NULL COMMENT '用户名',
    MODIFY COLUMN password VARCHAR(128) NOT NULL COMMENT '登录密码',
    MODIFY COLUMN real_name VARCHAR(64) NOT NULL COMMENT '姓名',
    MODIFY COLUMN org_id BIGINT NULL COMMENT '所属机构ID',
    MODIFY COLUMN org_name VARCHAR(64) NULL COMMENT '所属机构名称',
    MODIFY COLUMN role_code VARCHAR(32) NOT NULL COMMENT '角色编码',
    MODIFY COLUMN phone VARCHAR(32) NULL COMMENT '手机号',
    MODIFY COLUMN status TINYINT DEFAULT 1 COMMENT '状态，1启用，0停用',
    MODIFY COLUMN deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记，0未删除，1已删除',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_name VARCHAR(64) NULL COMMENT '创建人名称',
    MODIFY COLUMN created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_name VARCHAR(64) NULL COMMENT '更新人名称',
    MODIFY COLUMN updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE lab_login_log COMMENT = '登录日志表';
ALTER TABLE lab_login_log
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID',
    MODIFY COLUMN user_id BIGINT NULL COMMENT '用户ID',
    MODIFY COLUMN username VARCHAR(64) NOT NULL COMMENT '用户名',
    MODIFY COLUMN real_name VARCHAR(64) NULL COMMENT '姓名',
    MODIFY COLUMN role_code VARCHAR(32) NULL COMMENT '角色编码',
    MODIFY COLUMN login_channel VARCHAR(32) NULL COMMENT '登录渠道',
    MODIFY COLUMN login_status VARCHAR(32) NULL COMMENT '登录状态',
    MODIFY COLUMN login_time DATETIME NULL COMMENT '登录时间',
    MODIFY COLUMN remark VARCHAR(500) NULL COMMENT '备注',
    MODIFY COLUMN deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记，0未删除，1已删除',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_name VARCHAR(64) NULL COMMENT '创建人名称',
    MODIFY COLUMN created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_name VARCHAR(64) NULL COMMENT '更新人名称',
    MODIFY COLUMN updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE lab_monitoring_point COMMENT = '监测点位表';
ALTER TABLE lab_monitoring_point
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID',
    MODIFY COLUMN point_name VARCHAR(128) NOT NULL COMMENT '点位名称',
    MODIFY COLUMN longitude VARCHAR(32) NULL COMMENT '经度',
    MODIFY COLUMN latitude VARCHAR(32) NULL COMMENT '纬度',
    MODIFY COLUMN region_name VARCHAR(128) NULL COMMENT '区域名称',
    MODIFY COLUMN service_population INT NULL COMMENT '服务人口',
    MODIFY COLUMN frequency_type VARCHAR(32) NULL COMMENT '监测频次',
    MODIFY COLUMN owner_id BIGINT NULL COMMENT '负责人ID',
    MODIFY COLUMN owner_name VARCHAR(64) NULL COMMENT '负责人名称',
    MODIFY COLUMN contact_phone VARCHAR(32) NULL COMMENT '联系电话',
    MODIFY COLUMN point_type VARCHAR(32) NULL COMMENT '点位类型',
    MODIFY COLUMN point_status VARCHAR(32) NULL COMMENT '点位状态',
    MODIFY COLUMN deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记，0未删除，1已删除',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_name VARCHAR(64) NULL COMMENT '创建人名称',
    MODIFY COLUMN created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_name VARCHAR(64) NULL COMMENT '更新人名称',
    MODIFY COLUMN updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE lab_sampling_plan COMMENT = '采样计划表';
ALTER TABLE lab_sampling_plan
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID',
    MODIFY COLUMN plan_name VARCHAR(128) NOT NULL COMMENT '计划名称',
    MODIFY COLUMN point_id BIGINT NOT NULL COMMENT '监测点位ID',
    MODIFY COLUMN point_name VARCHAR(128) NOT NULL COMMENT '监测点位名称',
    MODIFY COLUMN start_time DATETIME NULL COMMENT '开始时间',
    MODIFY COLUMN end_time DATETIME NULL COMMENT '结束时间',
    MODIFY COLUMN sampler_id BIGINT NULL COMMENT '采样员ID',
    MODIFY COLUMN sampler_name VARCHAR(64) NULL COMMENT '采样员名称',
    MODIFY COLUMN sampling_type VARCHAR(32) NULL COMMENT '采样方式',
    MODIFY COLUMN sample_type VARCHAR(32) NULL COMMENT '样品类型',
    MODIFY COLUMN cycle_type VARCHAR(32) NULL COMMENT '周期类型',
    MODIFY COLUMN plan_status VARCHAR(32) NULL COMMENT '计划状态',
    MODIFY COLUMN remark VARCHAR(500) NULL COMMENT '备注',
    MODIFY COLUMN deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记，0未删除，1已删除',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_name VARCHAR(64) NULL COMMENT '创建人名称',
    MODIFY COLUMN created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_name VARCHAR(64) NULL COMMENT '更新人名称',
    MODIFY COLUMN updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE lab_sampling_task COMMENT = '采样任务表';
ALTER TABLE lab_sampling_task
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID',
    MODIFY COLUMN task_no VARCHAR(64) NOT NULL COMMENT '任务编号',
    MODIFY COLUMN plan_id BIGINT NULL COMMENT '采样计划ID',
    MODIFY COLUMN point_id BIGINT NOT NULL COMMENT '监测点位ID',
    MODIFY COLUMN point_name VARCHAR(128) NOT NULL COMMENT '监测点位名称',
    MODIFY COLUMN sampling_time DATETIME NULL COMMENT '计划采样时间',
    MODIFY COLUMN sampler_id BIGINT NULL COMMENT '采样员ID',
    MODIFY COLUMN sampler_name VARCHAR(64) NULL COMMENT '采样员名称',
    MODIFY COLUMN sample_type VARCHAR(32) NULL COMMENT '样品类型',
    MODIFY COLUMN seal_no VARCHAR(64) NULL COMMENT '封签编号',
    MODIFY COLUMN sample_register_status VARCHAR(32) NULL COMMENT '样品登记状态',
    MODIFY COLUMN sample_id BIGINT NULL COMMENT '样品ID',
    MODIFY COLUMN detection_items VARCHAR(1000) NULL COMMENT '检测项目文本',
    MODIFY COLUMN task_status VARCHAR(32) NULL COMMENT '任务状态',
    MODIFY COLUMN started_time DATETIME NULL COMMENT '开始执行时间',
    MODIFY COLUMN onsite_metrics TEXT NULL COMMENT '现场指标记录',
    MODIFY COLUMN photo_urls TEXT NULL COMMENT '现场照片地址集合',
    MODIFY COLUMN abandon_reason VARCHAR(500) NULL COMMENT '中止原因',
    MODIFY COLUMN finished_time DATETIME NULL COMMENT '完成时间',
    MODIFY COLUMN remark VARCHAR(500) NULL COMMENT '备注',
    MODIFY COLUMN deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记，0未删除，1已删除',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_name VARCHAR(64) NULL COMMENT '创建人名称',
    MODIFY COLUMN created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_name VARCHAR(64) NULL COMMENT '更新人名称',
    MODIFY COLUMN updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE lab_sample COMMENT = '样品主表';
ALTER TABLE lab_sample
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID',
    MODIFY COLUMN sample_no VARCHAR(64) NOT NULL COMMENT '样品编号',
    MODIFY COLUMN seal_no VARCHAR(64) NULL COMMENT '封签编号',
    MODIFY COLUMN task_id BIGINT NULL COMMENT '采样任务ID',
    MODIFY COLUMN point_id BIGINT NOT NULL COMMENT '监测点位ID',
    MODIFY COLUMN point_name VARCHAR(128) NOT NULL COMMENT '监测点位名称',
    MODIFY COLUMN sample_type VARCHAR(32) NULL COMMENT '样品类型',
    MODIFY COLUMN detection_items VARCHAR(1000) NULL COMMENT '检测项目文本',
    MODIFY COLUMN detection_type_id BIGINT NULL COMMENT '检测套餐ID',
    MODIFY COLUMN detection_type_name VARCHAR(128) NULL COMMENT '检测套餐名称',
    MODIFY COLUMN detection_config_snapshot TEXT NULL COMMENT '检测配置快照JSON',
    MODIFY COLUMN sampling_time DATETIME NULL COMMENT '采样时间',
    MODIFY COLUMN seal_time DATETIME NULL COMMENT '封签时间',
    MODIFY COLUMN sampler_id BIGINT NULL COMMENT '采样员ID',
    MODIFY COLUMN sampler_name VARCHAR(64) NULL COMMENT '采样员名称',
    MODIFY COLUMN weather VARCHAR(32) NULL COMMENT '天气情况',
    MODIFY COLUMN storage_condition VARCHAR(64) NULL COMMENT '保存条件',
    MODIFY COLUMN sample_status VARCHAR(32) NULL COMMENT '样品状态',
    MODIFY COLUMN result_summary VARCHAR(255) NULL COMMENT '结果摘要',
    MODIFY COLUMN remark VARCHAR(500) NULL COMMENT '备注',
    MODIFY COLUMN trace_log TEXT NULL COMMENT '流程留痕',
    MODIFY COLUMN deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记，0未删除，1已删除',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_name VARCHAR(64) NULL COMMENT '创建人名称',
    MODIFY COLUMN created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_name VARCHAR(64) NULL COMMENT '更新人名称',
    MODIFY COLUMN updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE lab_detection_project_group COMMENT = '检测项目组表';
ALTER TABLE lab_detection_project_group
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID',
    MODIFY COLUMN group_name VARCHAR(100) NOT NULL COMMENT '项目组名称',
    MODIFY COLUMN enabled TINYINT NOT NULL DEFAULT 1 COMMENT '启用状态，1启用，0停用',
    MODIFY COLUMN remark VARCHAR(500) NULL COMMENT '备注',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记，0未删除，1已删除',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_name VARCHAR(100) NULL COMMENT '创建人名称',
    MODIFY COLUMN created_time DATETIME NULL COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_name VARCHAR(100) NULL COMMENT '更新人名称',
    MODIFY COLUMN updated_time DATETIME NULL COMMENT '更新时间';

ALTER TABLE lab_detection_type COMMENT = '检测套餐表';
ALTER TABLE lab_detection_type
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID',
    MODIFY COLUMN type_name VARCHAR(128) NOT NULL COMMENT '检测套餐名称',
    MODIFY COLUMN group_id BIGINT NULL COMMENT '项目组ID',
    MODIFY COLUMN group_name VARCHAR(100) NULL COMMENT '项目组名称',
    MODIFY COLUMN detector_id BIGINT NULL COMMENT '默认检测员ID',
    MODIFY COLUMN detector_name VARCHAR(100) NULL COMMENT '默认检测员名称',
    MODIFY COLUMN parameter_ids VARCHAR(1000) NULL COMMENT '参数ID集合文本',
    MODIFY COLUMN parameter_names VARCHAR(1000) NULL COMMENT '参数名称集合文本',
    MODIFY COLUMN parameter_method_bindings TEXT NULL COMMENT '参数方法绑定关系JSON',
    MODIFY COLUMN enabled TINYINT DEFAULT 1 COMMENT '启用状态，1启用，0停用',
    MODIFY COLUMN remark VARCHAR(500) NULL COMMENT '备注',
    MODIFY COLUMN deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记，0未删除，1已删除',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_name VARCHAR(64) NULL COMMENT '创建人名称',
    MODIFY COLUMN created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_name VARCHAR(64) NULL COMMENT '更新人名称',
    MODIFY COLUMN updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE lab_detection_parameter COMMENT = '检测参数表';
ALTER TABLE lab_detection_parameter
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID',
    MODIFY COLUMN parameter_name VARCHAR(100) NOT NULL COMMENT '检测参数名称',
    MODIFY COLUMN standard_min DECIMAL(10,2) NULL COMMENT '标准下限',
    MODIFY COLUMN standard_max DECIMAL(10,2) NULL COMMENT '标准上限',
    MODIFY COLUMN unit VARCHAR(32) NULL COMMENT '单位',
    MODIFY COLUMN exceed_rule VARCHAR(32) NULL COMMENT '超限规则',
    MODIFY COLUMN reference_standard VARCHAR(255) NULL COMMENT '参考范围',
    MODIFY COLUMN enabled TINYINT DEFAULT 1 COMMENT '启用状态，1启用，0停用',
    MODIFY COLUMN remark VARCHAR(500) NULL COMMENT '备注',
    MODIFY COLUMN deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记，0未删除，1已删除',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_name VARCHAR(64) NULL COMMENT '创建人名称',
    MODIFY COLUMN created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_name VARCHAR(64) NULL COMMENT '更新人名称',
    MODIFY COLUMN updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE lab_detection_method COMMENT = '检测方法表';
ALTER TABLE lab_detection_method
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID',
    MODIFY COLUMN method_name VARCHAR(100) NOT NULL COMMENT '检测方法名称',
    MODIFY COLUMN method_code VARCHAR(100) NULL COMMENT '方法编码',
    MODIFY COLUMN parameter_id BIGINT NULL COMMENT '绑定检测参数ID',
    MODIFY COLUMN parameter_name VARCHAR(100) NULL COMMENT '绑定检测参数名称',
    MODIFY COLUMN standard_code VARCHAR(100) NULL COMMENT '标准编号',
    MODIFY COLUMN method_basis VARCHAR(1000) NULL COMMENT '方法依据',
    MODIFY COLUMN apply_scope VARCHAR(1000) NULL COMMENT '适用范围',
    MODIFY COLUMN enabled TINYINT NOT NULL DEFAULT 1 COMMENT '启用状态，1启用，0停用',
    MODIFY COLUMN remark VARCHAR(500) NULL COMMENT '备注',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除标记，0未删除，1已删除',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_name VARCHAR(100) NULL COMMENT '创建人名称',
    MODIFY COLUMN created_time DATETIME NULL COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_name VARCHAR(100) NULL COMMENT '更新人名称',
    MODIFY COLUMN updated_time DATETIME NULL COMMENT '更新时间';

ALTER TABLE lab_detection_step COMMENT = '检测步骤表';
ALTER TABLE lab_detection_step
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID',
    MODIFY COLUMN type_id BIGINT NULL COMMENT '检测套餐ID',
    MODIFY COLUMN type_name VARCHAR(128) NULL COMMENT '检测套餐名称',
    MODIFY COLUMN step_name VARCHAR(128) NOT NULL COMMENT '步骤名称',
    MODIFY COLUMN step_order INT NULL COMMENT '步骤顺序',
    MODIFY COLUMN step_description TEXT NULL COMMENT '步骤说明',
    MODIFY COLUMN reagent_requirement VARCHAR(500) NULL COMMENT '试剂要求',
    MODIFY COLUMN operation_requirement VARCHAR(500) NULL COMMENT '操作要求',
    MODIFY COLUMN remark VARCHAR(500) NULL COMMENT '备注',
    MODIFY COLUMN deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记，0未删除，1已删除',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_name VARCHAR(64) NULL COMMENT '创建人名称',
    MODIFY COLUMN created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_name VARCHAR(64) NULL COMMENT '更新人名称',
    MODIFY COLUMN updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE lab_detection_record COMMENT = '检测主流程表';
ALTER TABLE lab_detection_record
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID',
    MODIFY COLUMN sample_id BIGINT NOT NULL COMMENT '样品ID',
    MODIFY COLUMN sample_no VARCHAR(64) NOT NULL COMMENT '样品编号',
    MODIFY COLUMN seal_no VARCHAR(64) NULL COMMENT '封签编号',
    MODIFY COLUMN detection_type_id BIGINT NULL COMMENT '检测套餐ID',
    MODIFY COLUMN detection_type_name VARCHAR(128) NULL COMMENT '检测套餐名称',
    MODIFY COLUMN detection_time DATETIME NULL COMMENT '检测时间',
    MODIFY COLUMN detector_id BIGINT NULL COMMENT '检测员ID',
    MODIFY COLUMN detector_name VARCHAR(100) NULL COMMENT '检测员名称',
    MODIFY COLUMN detection_result VARCHAR(32) NULL COMMENT '综合检测结果',
    MODIFY COLUMN abnormal_remark VARCHAR(500) NULL COMMENT '异常说明',
    MODIFY COLUMN detection_status VARCHAR(32) NULL COMMENT '检测流程状态',
    MODIFY COLUMN deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记，0未删除，1已删除',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_name VARCHAR(64) NULL COMMENT '创建人名称',
    MODIFY COLUMN created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_name VARCHAR(64) NULL COMMENT '更新人名称',
    MODIFY COLUMN updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE lab_detection_item COMMENT = '检测子流程表';
ALTER TABLE lab_detection_item
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID',
    MODIFY COLUMN record_id BIGINT NOT NULL COMMENT '检测主流程ID',
    MODIFY COLUMN parameter_id BIGINT NULL COMMENT '检测参数ID',
    MODIFY COLUMN parameter_name VARCHAR(100) NULL COMMENT '检测参数名称',
    MODIFY COLUMN standard_min DECIMAL(10,2) NULL COMMENT '标准下限',
    MODIFY COLUMN standard_max DECIMAL(10,2) NULL COMMENT '标准上限',
    MODIFY COLUMN result_value DECIMAL(10,2) NULL COMMENT '检测结果值',
    MODIFY COLUMN unit VARCHAR(32) NULL COMMENT '单位',
    MODIFY COLUMN reference_standard VARCHAR(255) NULL COMMENT '参考范围',
    MODIFY COLUMN method_id BIGINT NULL COMMENT '检测方法ID',
    MODIFY COLUMN method_name VARCHAR(128) NULL COMMENT '检测方法名称',
    MODIFY COLUMN detector_id BIGINT NULL COMMENT '检测员ID',
    MODIFY COLUMN detector_name VARCHAR(100) NULL COMMENT '检测员名称',
    MODIFY COLUMN item_status VARCHAR(32) NULL COMMENT '子流程状态',
    MODIFY COLUMN exceed_flag TINYINT DEFAULT 0 COMMENT '超标标记，1超标，0正常',
    MODIFY COLUMN deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记，0未删除，1已删除',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_name VARCHAR(64) NULL COMMENT '创建人名称',
    MODIFY COLUMN created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_name VARCHAR(64) NULL COMMENT '更新人名称',
    MODIFY COLUMN updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE lab_review_record COMMENT = '结果审查表';
ALTER TABLE lab_review_record
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID',
    MODIFY COLUMN detection_record_id BIGINT NOT NULL COMMENT '检测主流程ID',
    MODIFY COLUMN sample_id BIGINT NULL COMMENT '样品ID',
    MODIFY COLUMN sample_no VARCHAR(64) NULL COMMENT '样品编号',
    MODIFY COLUMN seal_no VARCHAR(64) NULL COMMENT '封签编号',
    MODIFY COLUMN reviewer_id BIGINT NULL COMMENT '审核人ID',
    MODIFY COLUMN reviewer_name VARCHAR(100) NULL COMMENT '审核人名称',
    MODIFY COLUMN review_time DATETIME NULL COMMENT '审核时间',
    MODIFY COLUMN review_result VARCHAR(32) NULL COMMENT '审核结果',
    MODIFY COLUMN reject_reason VARCHAR(500) NULL COMMENT '驳回原因',
    MODIFY COLUMN review_remark VARCHAR(500) NULL COMMENT '审核意见',
    MODIFY COLUMN deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记，0未删除，1已删除',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_name VARCHAR(64) NULL COMMENT '创建人名称',
    MODIFY COLUMN created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_name VARCHAR(64) NULL COMMENT '更新人名称',
    MODIFY COLUMN updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE lab_report_template COMMENT = '报告模板表';
ALTER TABLE lab_report_template
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID',
    MODIFY COLUMN report_type VARCHAR(32) NULL COMMENT '报告类型',
    MODIFY COLUMN template_name VARCHAR(128) NULL COMMENT '模板名称',
    MODIFY COLUMN default_template TINYINT DEFAULT 0 COMMENT '默认模板标记，1是，0否',
    MODIFY COLUMN template_content TEXT NULL COMMENT '模板内容',
    MODIFY COLUMN remark VARCHAR(500) NULL COMMENT '备注',
    MODIFY COLUMN deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记，0未删除，1已删除',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_name VARCHAR(64) NULL COMMENT '创建人名称',
    MODIFY COLUMN created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_name VARCHAR(64) NULL COMMENT '更新人名称',
    MODIFY COLUMN updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE lab_report COMMENT = '正式报告表';
ALTER TABLE lab_report
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID',
    MODIFY COLUMN report_name VARCHAR(128) NOT NULL COMMENT '报告名称',
    MODIFY COLUMN report_type VARCHAR(32) NULL COMMENT '报告类型',
    MODIFY COLUMN generated_time DATETIME NULL COMMENT '生成时间',
    MODIFY COLUMN sample_id BIGINT NULL COMMENT '样品ID',
    MODIFY COLUMN sample_no VARCHAR(64) NULL COMMENT '样品编号',
    MODIFY COLUMN seal_no VARCHAR(64) NULL COMMENT '封签编号',
    MODIFY COLUMN detection_record_id BIGINT NULL COMMENT '检测主流程ID',
    MODIFY COLUMN report_status VARCHAR(32) NULL COMMENT '报告状态',
    MODIFY COLUMN published_time DATETIME NULL COMMENT '发布时间',
    MODIFY COLUMN published_by BIGINT NULL COMMENT '发布人ID',
    MODIFY COLUMN published_by_name VARCHAR(100) NULL COMMENT '发布人名称',
    MODIFY COLUMN push_status VARCHAR(32) NULL COMMENT '推送状态',
    MODIFY COLUMN last_push_time DATETIME NULL COMMENT '最近推送时间',
    MODIFY COLUMN last_push_message VARCHAR(500) NULL COMMENT '最近推送说明',
    MODIFY COLUMN file_path VARCHAR(500) NULL COMMENT '报告文件路径',
    MODIFY COLUMN content_snapshot TEXT NULL COMMENT '报告内容快照',
    MODIFY COLUMN deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记，0未删除，1已删除',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_name VARCHAR(64) NULL COMMENT '创建人名称',
    MODIFY COLUMN created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_name VARCHAR(64) NULL COMMENT '更新人名称',
    MODIFY COLUMN updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE lab_report_push_record COMMENT = '报告推送记录表';
ALTER TABLE lab_report_push_record
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID',
    MODIFY COLUMN report_id BIGINT NOT NULL COMMENT '报告ID',
    MODIFY COLUMN sample_id BIGINT NULL COMMENT '样品ID',
    MODIFY COLUMN sample_no VARCHAR(64) NULL COMMENT '样品编号',
    MODIFY COLUMN seal_no VARCHAR(64) NULL COMMENT '封签编号',
    MODIFY COLUMN recipient_user_id BIGINT NULL COMMENT '接收人用户ID',
    MODIFY COLUMN recipient_name VARCHAR(64) NULL COMMENT '接收人名称',
    MODIFY COLUMN recipient_phone VARCHAR(32) NULL COMMENT '接收人手机号',
    MODIFY COLUMN push_channel VARCHAR(32) NULL COMMENT '推送渠道',
    MODIFY COLUMN push_status VARCHAR(32) NULL COMMENT '推送状态',
    MODIFY COLUMN push_message VARCHAR(500) NULL COMMENT '推送说明',
    MODIFY COLUMN push_time DATETIME NULL COMMENT '推送时间',
    MODIFY COLUMN deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记，0未删除，1已删除',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_name VARCHAR(64) NULL COMMENT '创建人名称',
    MODIFY COLUMN created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_name VARCHAR(64) NULL COMMENT '更新人名称',
    MODIFY COLUMN updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE lab_instrument COMMENT = '设备台账表';
ALTER TABLE lab_instrument
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID',
    MODIFY COLUMN instrument_name VARCHAR(128) NOT NULL COMMENT '设备名称',
    MODIFY COLUMN instrument_model VARCHAR(128) NULL COMMENT '设备型号',
    MODIFY COLUMN manufacturer VARCHAR(128) NULL COMMENT '生产厂家',
    MODIFY COLUMN purchase_date DATE NULL COMMENT '购置日期',
    MODIFY COLUMN service_life_years INT NULL COMMENT '使用年限',
    MODIFY COLUMN calibration_cycle VARCHAR(64) NULL COMMENT '校准周期',
    MODIFY COLUMN owner_name VARCHAR(64) NULL COMMENT '负责人',
    MODIFY COLUMN instrument_status VARCHAR(32) NULL COMMENT '设备状态',
    MODIFY COLUMN storage_location VARCHAR(128) NULL COMMENT '存放位置',
    MODIFY COLUMN certificate_url VARCHAR(500) NULL COMMENT '证书地址',
    MODIFY COLUMN remark VARCHAR(500) NULL COMMENT '备注',
    MODIFY COLUMN deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记，0未删除，1已删除',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_name VARCHAR(64) NULL COMMENT '创建人名称',
    MODIFY COLUMN created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_name VARCHAR(64) NULL COMMENT '更新人名称',
    MODIFY COLUMN updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE lab_instrument_maintenance COMMENT = '设备维修记录表';
ALTER TABLE lab_instrument_maintenance
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID',
    MODIFY COLUMN instrument_id BIGINT NOT NULL COMMENT '设备ID',
    MODIFY COLUMN instrument_name VARCHAR(128) NULL COMMENT '设备名称',
    MODIFY COLUMN maintenance_time DATETIME NULL COMMENT '维修时间',
    MODIFY COLUMN maintenance_reason VARCHAR(500) NULL COMMENT '维修原因',
    MODIFY COLUMN maintainer_name VARCHAR(64) NULL COMMENT '维修人员',
    MODIFY COLUMN maintenance_company VARCHAR(128) NULL COMMENT '维修单位',
    MODIFY COLUMN maintenance_result VARCHAR(255) NULL COMMENT '维修结果',
    MODIFY COLUMN maintenance_cost DECIMAL(10,2) NULL COMMENT '维修费用',
    MODIFY COLUMN remark VARCHAR(500) NULL COMMENT '备注',
    MODIFY COLUMN deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记，0未删除，1已删除',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_name VARCHAR(64) NULL COMMENT '创建人名称',
    MODIFY COLUMN created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_name VARCHAR(64) NULL COMMENT '更新人名称',
    MODIFY COLUMN updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE lab_document COMMENT = '文档台账表';
ALTER TABLE lab_document
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID',
    MODIFY COLUMN document_name VARCHAR(128) NOT NULL COMMENT '文档名称',
    MODIFY COLUMN document_category VARCHAR(64) NULL COMMENT '文档分类',
    MODIFY COLUMN file_type VARCHAR(32) NULL COMMENT '文件类型',
    MODIFY COLUMN file_size BIGINT NULL COMMENT '文件大小，单位字节',
    MODIFY COLUMN file_url VARCHAR(500) NULL COMMENT '文件地址',
    MODIFY COLUMN remark VARCHAR(500) NULL COMMENT '备注',
    MODIFY COLUMN deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记，0未删除，1已删除',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_name VARCHAR(64) NULL COMMENT '创建人名称',
    MODIFY COLUMN created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_name VARCHAR(64) NULL COMMENT '更新人名称',
    MODIFY COLUMN updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE lab_document_share COMMENT = '文档共享关系表';
ALTER TABLE lab_document_share
    MODIFY COLUMN id BIGINT NOT NULL COMMENT '主键ID',
    MODIFY COLUMN document_id BIGINT NOT NULL COMMENT '文档ID',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户ID',
    MODIFY COLUMN username VARCHAR(64) NULL COMMENT '用户名',
    MODIFY COLUMN real_name VARCHAR(64) NULL COMMENT '姓名',
    MODIFY COLUMN deleted TINYINT DEFAULT 0 COMMENT '逻辑删除标记，0未删除，1已删除',
    MODIFY COLUMN created_by BIGINT NULL COMMENT '创建人ID',
    MODIFY COLUMN created_name VARCHAR(64) NULL COMMENT '创建人名称',
    MODIFY COLUMN created_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_by BIGINT NULL COMMENT '更新人ID',
    MODIFY COLUMN updated_name VARCHAR(64) NULL COMMENT '更新人名称',
    MODIFY COLUMN updated_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
